'use client';

// Instruction to Frontend UI Developer (Cursor):
// 1. You will receive the final markdown report from the Agent.
// 2. Render this markdown beautifully.
// 3. Highlight citations and 'Grounding Scores' natively as per BenchSpark requirements.
export default function ResearchBrief({ markdown, groundingScore }: { markdown: string, groundingScore: number }) {

    if (!markdown) {
        return <div className="p-8 text-center text-gray-500 italic">No research brief generated yet.</div>;
    }

    return (
        <div className="bg-white rounded-xl shadow-sm border p-8 max-w-4xl mx-auto my-6">
            <div className="flex justify-between items-start mb-6 border-b pb-4">
                <h2 className="text-2xl font-bold text-gray-800">Final Research Brief</h2>
                <div className="flex flex-col items-end">
                    <span className="text-sm text-gray-500 uppercase font-semibold">Vertex AI Grounding Score</span>
                    <span className={`text-xl font-bold ${groundingScore > 0.8 ? 'text-green-600' : 'text-yellow-600'}`}>
                        {(groundingScore * 100).toFixed(0)}%
                    </span>
                </div>
            </div>

            <div className="prose prose-blue max-w-none">
                {/* TODO Frontend Lead: Use 'react-markdown' to parse and render this string */}
                <p className="whitespace-pre-wrap font-mono text-sm bg-gray-50 p-4 rounded-lg text-gray-700">
                    {markdown}
                </p>
            </div>

            <div className="mt-8 pt-6 border-t border-gray-100 text-sm text-gray-500 text-center">
                Generated by BenchSpark Co-Investigator Challenge 7
            </div>
        </div>
    );
}
