'use client';

import { useMemo } from 'react';

interface ResearchBriefProps {
    markdown: string;
}

export default function ResearchBrief({ markdown }: ResearchBriefProps) {
    if (!markdown) {
        return (
            <div className="glass-card p-12 text-center animate-fade-in">
                <div className="text-4xl mb-3 opacity-30">📋</div>
                <p className="text-sm" style={{ color: 'var(--text-muted)' }}>
                    No research brief generated yet.
                </p>
                <p className="text-xs mt-1" style={{ color: 'var(--text-muted)' }}>
                    The final brief will appear here once the investigation is complete.
                </p>
            </div>
        );
    }

    return (
        <div className="glass-card p-6 animate-slide-up space-y-5">
            {/* Header */}
            <div className="flex items-start justify-between gap-4 pb-4" style={{ borderBottom: '1px solid var(--border-default)' }}>
                <div>
                    <h2 className="text-lg font-bold" style={{ color: 'var(--text-primary)' }}>
                        Research Summary
                    </h2>
                    <p className="text-xs mt-0.5" style={{ color: 'var(--text-muted)' }}>
                        Generated by Co-Investigator AI Research Assistant
                    </p>
                </div>
            </div>

            {/* Markdown Content */}
            <div className="prose-dark">
                <SimpleMarkdown content={markdown} />
            </div>

            {/* Footer */}
            <div
                className="pt-4 flex items-center justify-between text-[10px]"
                style={{ borderTop: '1px solid var(--border-default)', color: 'var(--text-muted)' }}
            >
                <span>Generated by BenchSpark Co-Investigator — Challenge 7</span>
                <button className="btn-primary text-[10px] px-3 py-1.5 rounded-lg">
                    Export PDF
                </button>
            </div>
        </div>
    );
}



/* ---- Simple Markdown Renderer ---- */
function SimpleMarkdown({ content }: { content: string }) {
    const elements = useMemo(() => parseMarkdown(content), [content]);
    return <>{elements}</>;
}

function parseMarkdown(md: string): React.ReactNode[] {
    const lines = md.split('\n');
    const nodes: React.ReactNode[] = [];
    let i = 0;
    let key = 0;

    while (i < lines.length) {
        const line = lines[i];

        // Horizontal rule
        if (/^---+$/.test(line.trim())) {
            nodes.push(<hr key={key++} />);
            i++;
            continue;
        }

        // Headers
        if (line.startsWith('### ')) {
            nodes.push(<h3 key={key++}>{inlineFormat(line.slice(4))}</h3>);
            i++;
            continue;
        }
        if (line.startsWith('## ')) {
            nodes.push(<h2 key={key++}>{inlineFormat(line.slice(3))}</h2>);
            i++;
            continue;
        }
        if (line.startsWith('# ')) {
            nodes.push(<h1 key={key++}>{inlineFormat(line.slice(2))}</h1>);
            i++;
            continue;
        }

        // Table
        if (line.includes('|') && i + 1 < lines.length && /^\|[\s\-:|]+\|$/.test(lines[i + 1].trim())) {
            const headerCells = line.split('|').filter(Boolean).map(c => c.trim());
            i += 2; // skip header + separator
            const rows: string[][] = [];
            while (i < lines.length && lines[i].includes('|') && lines[i].trim() !== '') {
                rows.push(lines[i].split('|').filter(Boolean).map(c => c.trim()));
                i++;
            }
            nodes.push(
                <table key={key++}>
                    <thead>
                        <tr>{headerCells.map((h, j) => <th key={j}>{inlineFormat(h)}</th>)}</tr>
                    </thead>
                    <tbody>
                        {rows.map((row, ri) => (
                            <tr key={ri}>{row.map((cell, ci) => <td key={ci}>{inlineFormat(cell)}</td>)}</tr>
                        ))}
                    </tbody>
                </table>
            );
            continue;
        }

        // Unordered list items
        if (/^[-*•]\s/.test(line.trim())) {
            const items: string[] = [];
            while (i < lines.length && /^[-*•]\s/.test(lines[i].trim())) {
                items.push(lines[i].trim().slice(2));
                i++;
            }
            nodes.push(
                <ul key={key++}>{items.map((item, j) => <li key={j}>{inlineFormat(item)}</li>)}</ul>
            );
            continue;
        }

        // Numbered list items
        if (/^\d+\.\s/.test(line.trim())) {
            const items: string[] = [];
            while (i < lines.length && /^\d+\.\s/.test(lines[i].trim())) {
                items.push(lines[i].trim().replace(/^\d+\.\s/, ''));
                i++;
            }
            nodes.push(
                <ol key={key++}>{items.map((item, j) => <li key={j}>{inlineFormat(item)}</li>)}</ol>
            );
            continue;
        }

        // Empty line
        if (line.trim() === '') {
            i++;
            continue;
        }

        // Paragraph
        nodes.push(<p key={key++}>{inlineFormat(line)}</p>);
        i++;
    }

    return nodes;
}

function inlineFormat(text: string): React.ReactNode {
    // Split by bold, italic, code patterns and reconstruct
    const parts: React.ReactNode[] = [];
    let remaining = text;
    let partKey = 0;

    while (remaining.length > 0) {
        // Bold
        const boldMatch = remaining.match(/\*\*(.*?)\*\*/);
        // Italic
        const italicMatch = remaining.match(/\*(.*?)\*/);
        // Code
        const codeMatch = remaining.match(/`(.*?)`/);

        // Find earliest match
        const matches = [
            boldMatch ? { type: 'bold', match: boldMatch, idx: boldMatch.index! } : null,
            italicMatch && (!boldMatch || italicMatch.index! < boldMatch.index!) ? { type: 'italic', match: italicMatch, idx: italicMatch.index! } : null,
            codeMatch ? { type: 'code', match: codeMatch, idx: codeMatch.index! } : null,
        ].filter(Boolean) as { type: string; match: RegExpMatchArray; idx: number }[];

        if (matches.length === 0) {
            parts.push(remaining);
            break;
        }

        matches.sort((a, b) => a.idx - b.idx);
        const earliest = matches[0];

        if (earliest.idx > 0) {
            parts.push(remaining.slice(0, earliest.idx));
        }

        if (earliest.type === 'bold') {
            parts.push(<strong key={partKey++}>{earliest.match[1]}</strong>);
        } else if (earliest.type === 'italic') {
            parts.push(<em key={partKey++}>{earliest.match[1]}</em>);
        } else if (earliest.type === 'code') {
            parts.push(<code key={partKey++}>{earliest.match[1]}</code>);
        }

        remaining = remaining.slice(earliest.idx + earliest.match[0].length);
    }

    return parts.length === 1 ? parts[0] : <>{parts}</>;
}
