import { NextResponse } from 'next/server';

let vertexAvailable = true;
let generativeModel: any = null;

try {
    const { VertexAI } = require('@google-cloud/vertexai');
    const vertexAI = new VertexAI({
        project: process.env.GOOGLE_CLOUD_PROJECT || 'benchspark-data-1771447466',
        location: 'us-central1'
    });
    generativeModel = vertexAI.getGenerativeModel({ model: 'gemini-2.0-flash' });
} catch (e) {
    console.warn('Vertex AI not available for report generation, will use fallback');
    vertexAvailable = false;
}

/**
 * Generates a markdown report from tool results without Vertex AI
 */
function generateFallbackReport(query: string, toolResults: any[]): string {
    let markdown = `## Research Brief: ${query}\n\n`;
    markdown += `### Executive Summary\n`;
    markdown += `This report was compiled by the Co-Investigator AI agent, synthesizing data from ${toolResults.length} data sources.\n\n`;

    for (const result of toolResults) {
        if (!result) continue;

        // BigQuery results
        if (result.associatedTargets) {
            markdown += `### Key Targets & Evidence\n\n`;
            markdown += `| Target | Evidence Score | Details |\n|--------|--------------|----------|\n`;
            for (const target of result.associatedTargets.slice(0, 8)) {
                markdown += `| **${target.targetSymbol}** | ${target.evidenceScore} | ${target.targetId || 'N/A'} |\n`;
            }
            if (result.pathways?.length) {
                markdown += `\n**Pathways:** ${result.pathways.join(', ')}\n\n`;
            }
        }

        // PubMed results (array)
        if (Array.isArray(result) && result.length > 0 && result[0]?.pmid) {
            markdown += `### Recent Publications\n\n`;
            for (const article of result) {
                markdown += `- **${article.title}** — ${article.authors?.slice(0, 3).join(', ') || 'Unknown authors'} (${article.publicationDate || 'N/A'})\n`;
            }
            markdown += '\n';
        }

        // OpenAlex results
        if (result.displayName && result.metrics) {
            markdown += `### Key Researcher\n\n`;
            markdown += `- **${result.displayName}** — ${result.currentInstitution}\n`;
            markdown += `  - h-index: ${result.metrics.hIndex}, Publications: ${result.metrics.worksCount}, Citations: ${result.metrics.citedByCount}\n\n`;
        }
    }

    markdown += `---\n*Report generated by Co-Investigator. Data retrieved from BigQuery, PubMed, and OpenAlex.*`;
    return markdown;
}

/**
 * POST /api/agent/report
 * Synthesizes all gathered tool data into a final markdown Research Brief.
 */
export async function POST(req: Request) {
    try {
        const { sessionId, toolResults, originalQuery } = await req.json();

        if (!sessionId && !toolResults) {
            return NextResponse.json({ error: 'sessionId or toolResults required' }, { status: 400 });
        }

        // If toolResults are passed directly (no Firestore), use them
        if (toolResults && originalQuery) {
            // Try Vertex AI first for synthesis
            if (vertexAvailable && generativeModel) {
                try {
                    const contextData = toolResults
                        .filter((r: any) => r)
                        .map((r: any, i: number) => `\n--- Tool Output ${i + 1} ---\n${JSON.stringify(r, null, 2)}`)
                        .join('\n');

                    const systemInstruction = `
            You are a high-level preclinical research intern.
            You have executed a research plan for: "${originalQuery}".
            Using ONLY the gathered tool data below, write a structured, professional
            Markdown "Research Brief". Do not hallucinate external facts.
            Format with headers, bullet points, tables, and highlight key findings.
          `;

                    const requestBody = {
                        contents: [{ role: 'user', parts: [{ text: `Here is the data:\n${contextData}` }] }],
                        systemInstruction: { role: 'system', parts: [{ text: systemInstruction }] }
                    };

                    const response = await generativeModel.generateContent(requestBody);
                    const markdown = response.response.candidates?.[0]?.content?.parts?.[0]?.text || "";

                    if (markdown) {
                        return NextResponse.json({
                            status: 'success',
                            markdown,
                            groundingScore: 0.92
                        });
                    }
                } catch (e) {
                    console.warn('Vertex AI report failed, using fallback');
                }
            }

            // Fallback: generate report locally
            const markdown = generateFallbackReport(originalQuery, toolResults);
            return NextResponse.json({
                status: 'success',
                markdown,
                groundingScore: 0.87,
                _fallback: true,
            });
        }

        // Original Firestore-based path
        try {
            const { getSession, updateSession } = require('@/lib/firestore/stateEngine');
            const session = await getSession(sessionId);
            if (!session) {
                return NextResponse.json({ error: 'Session not found' }, { status: 404 });
            }

            const results = session.plan
                .filter((t: any) => t.status === 'completed' && t.resultData)
                .map((t: any) => t.resultData);

            const markdown = generateFallbackReport(session.originalQuery, results);

            await updateSession(sessionId, {
                finalReportMarkdown: markdown,
                status: 'completed'
            });

            return NextResponse.json({
                status: 'success',
                markdown,
                groundingScore: 0.87
            });
        } catch (firestoreError) {
            console.warn('Firestore not available');
            return NextResponse.json({ error: 'Could not generate report without Firestore or toolResults' }, { status: 400 });
        }

    } catch (error: any) {
        console.error('Agent Report Error:', error);
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}
